### ISSUE TITLE
demo rollback error

### ISSUE THREAD

**Issue by StephenMhYt** [alibaba/fescar#110]
我在orderService最后返回前抛了一个错，以便触发global rollback。所以global rollback应该包含三个branch rollback。但是storage服务在rollback时，出现了如下错误，而且是三次连续出现。最后结果导致只有storage服务rollback成功，其余两个服务回滚失败，undo_log里各有一条记录。
debug发现是在BranchRollbackResponse父类AbstractBranchEndResponse中，branchStatus变量为空，请问是何原因？
2019-01-16 14:08:56,099 [FESCAR] [NettyClientSelector_RMROLE_1] ERROR com.alibaba.fescar.core.rpc.netty.MessageCodecHandler[104] - com.alibaba.fescar.core.protocol.transaction.BranchRollbackResponse@27f6c583 encode error
java.lang.NullPointerException: null
	at com.alibaba.fescar.core.protocol.transaction.AbstractBranchEndResponse.doEncode(AbstractBranchEndResponse.java:40)
	at com.alibaba.fescar.core.protocol.AbstractResultMessage.encode(AbstractResultMessage.java:90)
	at com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.encode(MessageCodecHandler.java:88)
	at com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.encode(MessageCodecHandler.java:42)
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by StephenMhYt** [comment]
I saw the TC logs,it always rollback retrying,and always timeout.

**Comment by StephenMhYt** [comment]
我好像找到答案了，因为我是三个服务都在一台服务器上启动的，最终注册到server时，clientId都是一样的，这就导致通过branchId找到的都是一个ip，所以branch rollback都发送到了一台服务里，也就是storage branch收到了order的rollback消息，storage 服务在通过resourceId获取fescar的数据源代理对象时，当然就会获取不到，抛出异常（ShouldNeverHappenException 为RuntimeException）后也就没有设置BranchStatus，最终报错NullPointerException。这是一个bug啊
