### ISSUE TITLE
Fescar0.4.0 start failed with Nacos

### ISSUE THREAD

**Issue by xianwei** [alibaba/fescar#637]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Fescar0.4.0 start failed with Nacos

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Thu Mar 21 09:54:39 CST 2019 sun.misc.Launcher$AppClassLoader@58372a00 JM.Log:INFO Init JM logger with Slf4jLoggerFactory success, sun.misc.Launcher$AppClassLoader@58372a00
Thu Mar 21 09:54:39 CST 2019 sun.misc.Launcher$AppClassLoader@58372a00 JM.Log:INFO Log root path: C:\Users\sxw\logs\
Thu Mar 21 09:54:39 CST 2019 sun.misc.Launcher$AppClassLoader@58372a00 JM.Log:INFO Set nacos log path: C:\Users\sxw\logs\nacos
2019-03-21 09:54:39.051 INFO [main]com.alibaba.nacos.client.identify.CredentialWatcher.info:101 -[] [] [] No credential found
2019-03-21 09:54:40.266 INFO [main]c.a.fescar.core.rpc.netty.AbstractRpcRemotingServer.start:151 -Server started ...
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost]) tried
        at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:155)
        at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
        at com.alibaba.fescar.server.Server.main(Server.java:88)
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost]) tried
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:366)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
        at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
        at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:152)
        ... 2 more

```

### Ⅲ. Describe what you expected to happen
start fescar success

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. start nacos
2. fescar change 'file' to 'nacos'
3. execute nacos-config.sh
4. start fescar
5. console print: Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost]) tried

### Ⅴ. Anything else we need to know?
I have extra information with debugging fescar server .
Nacos returns content：malfomed ip config: localhost:8091:unknown_1.0_true_false_default

![9C468FC3-A35F-4491-95CB-40B54604024E](https://user-images.githubusercontent.com/3487614/54730356-6cf1c280-4bc3-11e9-931e-6efb21f62750.jpg)

### Ⅵ. Environment:

- JDK version : 1.8.0_131
- OS :windows7
- Others: fescar0.4.0  nacos0.9.0

**Comment by vikenlove** [comment]
fescar 0,4 version dependency nacos 0.8， so can't start it .

**Comment by xianwei** [comment]
> fescar 0,4 version dependency nacos 0.8， so can't start it .

oo，thanks

**Comment by vikenlove** [comment]
@xianwei could you show you C:\Users\sxw\logs\nacos\naming.log  for me ? fescar team tell me  the 0.8 can start success.

**Comment by xianwei** [comment]
> @xianwei could you show you C:\Users\sxw\logs\nacos\naming.log for me ? fescar team tell me the 0.8 can start success.
It is it.
[naming.log](https://github.com/alibaba/fescar/files/3003382/naming.log)

**Comment by vikenlove** [comment]
cluster":"default","ip":"sxw-PC","metadata":{}

you must config ip when you start your fescar server .

**Comment by xianwei** [comment]
> cluster":"default","ip":"sxw-PC","metadata":{}
> 
> you must config ip when you start your fescar server .

ok,thanks.

**Comment by xingfudeshi** [comment]
I'll close this issue,if you have further question,please comment on this issue.
