### ISSUE TITLE
Lack service.vgroup_mapping.user-{appid}-fescar-service-group?

### ISSUE THREAD

**Issue by sundong1982** [alibaba/fescar#681]
ERROR 33800 --- [           main] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5001 ms,op:GET,dataId:service.disableGlobalTransaction

2019-03-28 20:54:10.718 ERROR 33800 --- [imeoutChecker_1] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5001 ms,op:GET,dataId:service.vgroup_mapping.user-web-fescar-service-group
2019-03-28 20:54:10.718 ERROR 33800 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : no available server to connect.
2019-03-28 20:54:10.734 ERROR 33800 --- [imeoutChecker_1] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5000 ms,op:GET,dataId:service.vgroup_mapping.user-web-fescar-service-group
2019-03-28 20:54:10.734 ERROR 33800 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient    : no available server to connect.
2019-03-28 20:54:15.719 ERROR 33800 --- [imeoutChecker_1] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5000 ms,op:GET,dataId:service.vgroup_mapping.user-web-fescar-service-group
2019-03-28 20:54:15.719 ERROR 33800 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : no available server to connect.

配置在nacos上
nacos server是0.9.0 nacos client是0.9.1服务发现、配置中心都完全正常。
0.4.0版本的 fescar-server.sh上有这么一段代码  :"$REPO"/nacos-client-0.8.0.jar:"$REPO"/nacos-common-0.8.0.jar

从抛错来看是配置中缺少dataId:service.vgroup_mapping.user-web-fescar-service-group这个配置，由源码中的GlobalTransactionAutoConfiguration类生成

用了spring cloud
fescar的客户端和服务器端都是0.4.0
`        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-fescar</artifactId>
            <version>2.1.0.BUILD-SNAPSHOT</version>
        </dependency>`

在版本规划里看到0.2.0 已经支持spring cloud

#659  #616  好像也是同样问题

**Comment by sundong1982** [comment]
nacos上serverAddr的IP是docker的地址172.17.0.1  而不是机器的内网ip

**Comment by sundong1982** [comment]
加入如下代码依旧抛错
`@Configuration
public class FescarConfig {

    @Value("${spring.application.name}")
    private String applicationId;

    @Bean
    public GlobalTransactionScanner initGlobalTransactionScanner() {
        return new GlobalTransactionScanner(applicationId, "my_test_tx_group");
    }
}`

ERROR 37208 --- [           main] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5002 ms,op:GET,dataId:service.disableGlobalTransaction

2019-03-28 23:37:11.816 ERROR 37208 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : get channel from pool error.

com.alibaba.fescar.common.exception.FrameworkException: can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:245) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:60) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:38) ~[fescar-core-0.4.0.jar:na]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.doConnect(TmRpcClient.java:389) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.connect(TmRpcClient.java:324) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.reconnect(TmRpcClient.java:186) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.access$000(TmRpcClient.java:70) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient$1.run(TmRpcClient.java:165) ~[fescar-core-0.4.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.alibaba.fescar.common.exception.FrameworkException: connect failed, can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:240) ~[fescar-core-0.4.0.jar:na]
	... 16 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8091
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	... 2 common frames omitted
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 common frames omitted

2019-03-28 23:37:11.816 ERROR 37208 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient    : 0304

com.alibaba.fescar.common.exception.FrameworkException: can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:245) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:60) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:38) ~[fescar-core-0.4.0.jar:na]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:361) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:329) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.reconnect(RmRpcClient.java:212) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.access$000(RmRpcClient.java:64) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient$1.run(RmRpcClient.java:152) ~[fescar-core-0.4.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.alibaba.fescar.common.exception.FrameworkException: connect failed, can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:240) ~[fescar-core-0.4.0.jar:na]
	... 16 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8091
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	... 2 common frames omitted
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 common frames omitted

2019-03-28 23:37:11.817 ERROR 37208 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : 0101

com.alibaba.fescar.common.exception.FrameworkException: can not register TM,err:can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.doConnect(TmRpcClient.java:392) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.connect(TmRpcClient.java:324) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.reconnect(TmRpcClient.java:186) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.access$000(TmRpcClient.java:70) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient$1.run(TmRpcClient.java:165) ~[fescar-core-0.4.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2019-03-28 23:37:11.817 ERROR 37208 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient    : 0101

com.alibaba.fescar.common.exception.FrameworkException: can not register RM,err:can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:364) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:329) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.reconnect(RmRpcClient.java:212) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.access$000(RmRpcClient.java:64) ~[fescar-core-0.4.0.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient$1.run(RmRpcClient.java:152) ~[fescar-core-0.4.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.31.Final.jar:4.1.31.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by slievrly** [comment]
@sundong1982 Please specify the external ip parameter when starting fescar-server。

**Comment by sundong1982** [comment]
@slievrly 指定IP后依然是上述问题
`sh /opt/fescar-server/bin/fescar-server.sh 8091 /opt/fescar-server/data 192.168.1.102`

**Comment by sundong1982** [comment]
看了一下file的配置
换成file搞定了

service {
  #vgroup->rgroup
  #vgroup_mapping.my_test_tx_group = "localRgroup"
  vgroup_mapping.user-web-fescar-service-group = "localRgroup"
  #only support single node
  localRgroup.grouplist = "192.168.1.102:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  disableGlobalTransaction = false
}

没有disableGlobalTransaction = false这个值，手动添加下

之前没注意到官方给的naccos配置导入的vgroup_mapping.my_test_tx_group值为default，nacos那边改一下再加上localRgroup.grouplist = "192.168.1.102:8091"这个配置应该就毛病了。
