### ISSUE TITLE
can not connect to fescar-server.

### ISSUE THREAD

**Issue by csfrez** [alibaba/fescar#69]
The official demo, OrderServiceImpl, AccountServiceImpl, StorageServiceImpl, can be started normally, BusinessServiceImpl can also call the remote service normally, but when executing the specific update method, report **can not connect to fescar-server**, generated Xid is as follows xid: 10.96.2.106:0:200986881, fescar-server is a local service, the computer is 4 core 16G, win10, JDK1.8, use the latest code, please help analyze the specific reasons, thank you!
// 官方给出的demo中，OrderServiceImpl，AccountServiceImpl，StorageServiceImpl，都可以正常启动，BusinessServiceImpl也可以正常调用远程服务，但在执行具体的update方法时，报**can not connect to fescar-server**，生成的xid如下xid: 10.96.2.106:0:200986881，fescar-server为本地服务，电脑是4核16G，win10，JDK1.8，使用最新的代码，请帮忙分析一下具体原因，谢谢！
2019-01-12 10:27:06,950 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.tm.dubbo.StorageService - Storage Service Begin ... xid: 10.96.2.106:0:200986881
2019-01-12 10:27:13,164 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.RmRpcClient - will connect to 10.96.2.106:0
2019-01-12 10:27:13,166 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.RmRpcClient - RM will register :jdbc:mysql://47.106.93.140:3306/fescar
2019-01-12 10:27:13,169 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to {"address":"10.96.2.106:0","message":{"applicationId":"dubbo-demo-storage-service","byteBuffer":{"char":"\u0000","direct":false,"double":0.0,"float":0.0,"int":0,"long":0,"readOnly":false,"short":0},"resourceIds":"jdbc:mysql://47.106.93.140:3306/fescar","transactionServiceGroup":"my_test_tx_group","typeCode":103,"version":"0.1.0"},"transactionRole":"RMROLE"}
2019-01-12 10:27:13,174 [FESCAR] [NettyClientSelector_RMROLE_1] INFO  com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting - ChannelHandlerContext(RmRpcClient#0, [id: 0xe72b116f]) will closed
2019-01-12 10:27:13,209 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] ERROR com.alibaba.fescar.core.rpc.netty.RmRpcClient - 0304
com.alibaba.fescar.common.exception.FrameworkException: can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:241)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:63)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:1)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:354)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:322)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.getRemoteServerChannel(RmRpcClient.java:243)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:228)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:248)
	at com.alibaba.fescar.rm.datasource.DataSourceManager.branchRegister(DataSourceManager.java:57)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:157)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:129)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:60)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:37)
	at com.alibaba.fescar.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:50)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:70)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:32)
	at com.alibaba.fescar.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:69)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.alibaba.fescar.tm.dubbo.impl.StorageServiceImpl.deduct(StorageServiceImpl.java:48)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.fescar.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:57)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.fescar.common.exception.FrameworkException: connect failed, can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:236)
	... 53 common frames omitted
2019-01-12 10:27:13,239 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.RmRpcClient - will connect to 10.96.2.106:0
2019-01-12 10:27:13,241 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.RmRpcClient - RM will register :jdbc:mysql://47.106.93.140:3306/fescar
2019-01-12 10:27:13,244 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] INFO  com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to {"address":"10.96.2.106:0","message":{"applicationId":"dubbo-demo-storage-service","byteBuffer":{"char":"\u0000","direct":false,"double":0.0,"float":0.0,"int":0,"long":0,"readOnly":false,"short":0},"resourceIds":"jdbc:mysql://47.106.93.140:3306/fescar","transactionServiceGroup":"my_test_tx_group","typeCode":103,"version":"0.1.0"},"transactionRole":"RMROLE"}
2019-01-12 10:27:13,248 [FESCAR] [NettyClientSelector_RMROLE_1] INFO  com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting - ChannelHandlerContext(RmRpcClient#0, [id: 0x55929b63]) will closed
2019-01-12 10:27:13,251 [FESCAR] [DubboServerHandler-10.96.2.106:20882-thread-2] ERROR com.alibaba.fescar.core.rpc.netty.RmRpcClient - 0304
com.alibaba.fescar.common.exception.FrameworkException: can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:241)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:63)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:1)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:354)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:322)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.getRemoteServerChannel(RmRpcClient.java:243)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:228)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:248)
	at com.alibaba.fescar.rm.datasource.DataSourceManager.branchRegister(DataSourceManager.java:57)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:157)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:129)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.setAutoCommit(ConnectionProxy.java:176)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:68)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:37)
	at com.alibaba.fescar.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:50)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:70)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:32)
	at com.alibaba.fescar.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:69)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:798)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:591)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:858)
	at com.alibaba.fescar.tm.dubbo.impl.StorageServiceImpl.deduct(StorageServiceImpl.java:48)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.fescar.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:57)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.fescar.common.exception.FrameworkException: connect failed, can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:236)
	... 54 common frames omitted

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by csfrez** [comment]
目前定位到为题xid生成有问题，RootContext.bind()方法替换一下端口就可以了`xid = xid.replace("10.96.2.106:0", "10.96.2.106:8091");`就可以了

**Comment by csfrez** [comment]
问题原因找到了，启动fescar-server服务时必须指定端口， 要不然XID端口默认是0

**Comment by skyesx** [comment]
relate to #76
